# Generated by Django 5.1.2 on 2024-10-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='date_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.AlterField(
            model_name='alert',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
