# Generated by Django 5.1.2 on 2024-10-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_rename_date_time_alert_time_remove_alert_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='time',
        ),
        migrations.AddField(
            model_name='alert',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
