# Generated by Django 5.1.2 on 2024-10-15 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_remove_alert_time_alert_files_alert_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
