# Generated by Django 5.1.2 on 2024-10-15 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_alter_alert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
