# Generated by Django 5.1.1 on 2024-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_alter_alert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='recipients',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='alert',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
