# Generated by Django 5.1.1 on 2024-11-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_alert_recipients_alter_alert_files_alter_alert_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='files',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
