# Generated by Django 5.1.1 on 2024-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_alter_alert_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='recipients',
        ),
        migrations.AlterField(
            model_name='alert',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
