# Generated by Django 5.1.1 on 2024-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0012_alter_alert_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='recipients',
            field=models.JSONField(default=list),
        ),
    ]
