# Generated by Django 5.1.1 on 2024-11-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0013_alert_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='recipients',
        ),
    ]
