# Generated by Django 5.1.1 on 2024-09-26 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('incident_type', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('landmark', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('victim_name', models.CharField(max_length=255)),
                ('victim_age', models.IntegerField()),
                ('victim_sex', models.CharField(max_length=10)),
                ('spot_report', models.TextField()),
                ('duty', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
