# Generated by Django 5.1.1 on 2024-10-17 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='')),
                ('incident_type', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('landmark', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('victim_name', models.CharField(max_length=255)),
                ('victim_age', models.IntegerField()),
                ('victim_sex', models.CharField(max_length=10)),
                ('spot_report', models.TextField()),
                ('duty', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=10)),
            ],
        ),
    ]
