# Generated by Django 5.1.1 on 2024-10-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='remarks',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_name',
            field=models.CharField(default='Unknown Reporter', max_length=255),
        ),
    ]
