# Generated by Django 5.1.1 on 2024-09-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
