# Generated by Django 5.1.1 on 2024-10-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
