# Generated by Django 5.1.1 on 2024-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='duty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
